#指定字段值
指定字段值新增（订单 -- 备注）:
  method: POST
  route: /apis/crm-web/assign-field-value
  data:
    assignType: 1
    assignValue:
      extendJson:
        finalValueName:
      finalValue: '33'
    executeNow: 0
    targetFieldId: '756585730700087452'
    targetModuleId: '756585727382392835'
    triggeringAction: 1,2
    triggeringCondition:
      compareType: 1
      extendJson: {}
      logicOperator: OR
      module: ''
      conditions:
      - compareFieldCode: '0000000'
        compareType: 1
        conditions: []
        field: dingdanjine
        fieldId: '756585730700087501'
        fieldType: 3
        logicOperator:
        module: order
        operator: '='
        value: '12'
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      targetModuleId: '756585727382392835'
      targetModuleName: 订单
      targetFieldId: '756585730700087452'
      targetFieldName: 备注
      triggeringAction: 1,2
      assignType: 1
      assignValue:
        finalValue: '33'
        fieldCode: ''
        fieldName:
        expression: ''
        extendJson:
          finalValueName:
      triggeringConditionType: 1
      triggeringCondition:
        compareType: 1
        compareFieldCode: ''
        module: ''
        field: ''
        fieldType:
        operator: ''
        value:
        conditions:
        - compareType: 1
          compareFieldCode: '0000000'
          module: order
          field: dingdanjine
          fieldType: 3
          operator: '='
          value: '12'
          conditions: []
          logicOperator: ''
        logicOperator: OR

指定字段值目标模块查询:
  method: GET
  route: /apis/crm-web/assign-field-values/target-module
  data:
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
    - value: '756585727382392840'
      description: 开票申请
    - value: '756585727382392835'
      description: 订单
指定字段值数据分页查询:
  method: GET
  route: /apis/crm-web/assign-field-values
  data:
    pageIndex: 1
    pageSize: 10
    targetModuleId: 756585727382392840
    targetFieldId:
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      totalCount: 1
      pageSize: 10
      totalPage: 1
      currPage: 1
      list:
      - id: '764491216233566208'
        targetModuleId: '756585727382392840'
        targetModuleName: 开票申请
        targetFieldId: '756585730700087442'
        targetFieldName: 开票金额
        triggeringAction: 1,2
        assignType: 1
        assignValue:
          finalValue: '12'
          fieldCode: ''
          fieldName:
          expression: ''
          extendJson: []
        triggeringConditionType: 1
        triggeringCondition:
          compareType: 1
          compareFieldCode: ''
          module: ''
          field: ''
          fieldType:
          operator: ''
          value:
          conditions:
          - compareType: 1
            compareFieldCode: ''
            module: kaipiaoshenqing
            field: kaipiaozhuangtai
            fieldType: 4
            operator: '='
            value: 已开票
            conditions: []
            logicOperator: ''
          logicOperator: OR
指定字段值目标模块查询（开票申请）:
  method: GET
  route: /apis/crm-web/assign-field-values/target-field
  data:
    moduleId: 756585727382392840
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
    - value: '756585730700087442'
      description: 开票金额
指定字段值目标模块字段查询（开票申请 -- 开票金额）:
  method: GET
  route: /apis/crm-web/assign-field-values
  data:
    pageIndex: 1
    pageSize: 10
    targetModuleId: 756585727382392840
    targetFieldId: 756585730700087442
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      totalCount: 1
      pageSize: 10
      totalPage: 1
      currPage: 1
      list:
      - id: '764491216233566208'
        targetModuleId: '756585727382392840'
        targetModuleName: 开票申请
        targetFieldId: '756585730700087442'
        targetFieldName: 开票金额
        triggeringAction: 1,2
        assignType: 1
        assignValue:
          finalValue: '12'
          fieldCode: ''
          fieldName:
          expression: ''
          extendJson: []
        triggeringConditionType: 1
        triggeringCondition:
          compareType: 1
          compareFieldCode: ''
          module: ''
          field: ''
          fieldType:
          operator: ''
          value:
          conditions:
          - compareType: 1
            compareFieldCode: ''
            module: kaipiaoshenqing
            field: kaipiaozhuangtai
            fieldType: 4
            operator: '='
            value: 已开票
            conditions: []
            logicOperator: ''
          logicOperator: OR
指定字段值目标模块详情（开票申请）:
  method: GET
  route: /apis/crm-web/assign-field-value/764491216233566208
  data:
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      id: '764491216233566208'
      targetModuleId: '756585727382392840'
      targetModuleName: 开票申请
      targetFieldId: '756585730700087442'
      targetFieldName: 开票金额
      triggeringAction: 1,2
      assignType: 1
      assignValue:
        finalValue: '12'
        fieldCode: ''
        fieldName:
        expression: ''
        extendJson: []
      triggeringConditionType: 1
      triggeringCondition:
        compareType: 1
        compareFieldCode: ''
        module: ''
        field: ''
        fieldType:
        operator: ''
        value:
        conditions:
        - compareType: 1
          compareFieldCode: ''
          module: kaipiaoshenqing
          field: kaipiaozhuangtai
          fieldType: 4
          operator: '='
          value: 已开票
          conditions: []
          logicOperator: ''
        logicOperator: OR
指定字段值目标模块删除（订单）:
  method: DELETE
  route: /apis/crm-web/assign-field-values
  data:
  headers: {}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:

指定字段值触发条件修改（开票申请）:
  method: PUT
  route: /apis/crm-web/assign-field-value/764491216233566208/triggering-condition
  data:
    triggeringCondition:
      compareFieldCode:
      compareType: 1
      field:
      fieldType:
      logicOperator: OR
      module:
      operator:
      value:
      conditions:
      - compareFieldCode:
        compareType: 1
        conditions: []
        field: kaipiaozhuangtai
        fieldType: 4
        logicOperator:
        module: kaipiaoshenqing
        operator: '='
        value: 已开票
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      id: '764491216233566208'
      targetModuleId: '756585727382392840'
      targetModuleName: 开票申请
      targetFieldId: '756585730700087442'
      targetFieldName: 开票金额
      triggeringAction: 1,2
      assignType: 1
      assignValue:
        finalValue: '12'
        fieldCode: ''
        fieldName:
        expression: ''
        extendJson: []
      triggeringConditionType: 1
      triggeringCondition:
        compareType: 1
        compareFieldCode: ''
        module: ''
        field: ''
        fieldType:
        operator: ''
        value:
        conditions:
        - compareType: 1
          compareFieldCode: ''
          module: kaipiaoshenqing
          field: kaipiaozhuangtai
          fieldType: 4
          operator: '='
          value: 已开票
          conditions: []
          logicOperator: ''
        logicOperator: OR
指定字段值触发（开票申请新增 -- 指定值12）:
  method: POST
  route:
  - /apis/crm-web/module/kaipiaoshenqing/insert
  - /apis/crm-web/module/kaipiaoshenqing/list
  - /apis/crm-web/module/kaipiaoshenqing/
  data:
    dingdanmingcheng:
    fuwuxiangmu:
    kaipiaojine: ''
    kaipiaoqijian: '2020-12-01 18:18:56'
    kaipiaozhuangtai: 已开票
    kehumingcheng: '756597488315666432'
    liuchengzhidingrenyuan: []
    zhidingrenyuan1:
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      totalCount: 1
      pageSize: 10
      totalPage: 1
      currPage: 1
      list:
      - _createDept: api测试
        _createUser: 系统管理员
        _modifyDept:
        _modifyTime:
        _modifyUser:
        _principal: 系统管理员
        dingdanmingcheng:
        fuwuxiangmu:
        kaipiaojine: '12'
        kaipiaozhuangtai: 已开票
        kehumingcheng: 测试用户
        liuchengzhidingrenyuan: []
        zhidingrenyuan1:
指定字段值不触发（开票申请新增 -- 指定值12）:
  method: POST
  route:
  - /apis/crm-web/module/kaipiaoshenqing/insert
  - /apis/crm-web/module/kaipiaoshenqing/list
  - /apis/crm-web/module/kaipiaoshenqing/
  data:
    dingdanmingcheng:
    fuwuxiangmu:
    kaipiaojine: ''
    kaipiaoqijian: '2020-12-01 18:18:56'
    kaipiaozhuangtai: 未开票
    kehumingcheng: '756597488315666432'
    liuchengzhidingrenyuan: []
    zhidingrenyuan1:
  headers: {Content-Type: application/json}
  expectcode: 200
  expectresult:
    code: 0
    msg:
    data:
      totalCount: 1
      pageSize: 10
      totalPage: 1
      currPage: 1
      list:
      - _createDept: api测试
        _createUser: 系统管理员
        _modifyDept:
        _modifyTime:
        _modifyUser:
        _principal: 系统管理员
        dingdanmingcheng:
        fuwuxiangmu:
        kaipiaojine: ''
        kaipiaozhuangtai: 未开票
        kehumingcheng: 测试用户
        liuchengzhidingrenyuan: []
        zhidingrenyuan1:
